### ISSUE TITLE
Come up with theme proposals

### ISSUE THREAD

**Issue by tatarchm** [tatarchm/locoschool#8]

**Comment by voshch** [comment]
Proposal: Smart Home

Task: Develop a robot that might help you in your day-to-day life. Consider both autonomous and human-interacting scenarios.

Possible Functionalities:
- person/movement detection
- person following
- indoor exploration
- temperature/humidity reporting
- visiting set waypoints (IMU)

Assoc. Use Cases:
- greeting/doorbell
- robot pet
- patrolling and raising alerts
- high temperature alert (hairdryer triggered)
- return to base

**Comment by tatarchm** [comment]
I really like this topic suggestion, better than the "city of the future" actually. There are endless small tasks one can come up with for first half of the course. And the final project can be a combination of robotics and IoT, depending on what each specific group is excited about. Also, this is a good basis for their independent tinkering in the future - in the end, smart home projects is what Arduino is all about.

**Comment by tatarchm** [comment]
@NColdGit what do you think? If this looks fine, I will write a course announcement draft based on the "smart home" idea.

**Comment by NColdGit** [comment]
I think it is an interesting direction for the course
